### ISSUE TITLE
Building the Distribution File

### ISSUE THREAD

**Issue by system-operator** [WesterosCraftCode/ElectronLauncher#11]
Is there an easy way to build the modules section of the distribution.json?

Love the launcher.

**Comment by dscalzi** [comment]
It has to be done manually. Theoretically I could build some sort of tool to do it, but don't expect that anytime soon.

**Comment by system-operator** [comment]
Any tips on automation of getting the main class name? Please?

**Comment by dscalzi** [comment]
The main class is always launchwrapper.

**Comment by dscalzi** [comment]
Also, please fork this repository or expressly credit the authors.

@system-operator

**Comment by system-operator** [comment]
@dscalzi I mean the groupID you are using as the ID >>  "id": "mezz:jei:1.11.2-4.5.1.296"

I can't really see any way to "automate" this. The rest is easy, as the info is inside the jar's MCMOD info file.

And yes, I would be glad to fork, if I can see a use for it. As of now, theres just no way I am going to spend the next several days trying to find all my class names for all 250 mods.

**Comment by dscalzi** [comment]
It's not if you can see a use for it. Either fork or expressly credit the authors.

All you would have to do is unzip the jar file and read the mcmod file. You don't need the main class (why would you?) - you need the maven identifier. It does not need to be the exact one, we store mods maven style as indicated in the documentation. Please read that.

**Comment by system-operator** [comment]
The mcmod info file is blank in 60% of the jar on Curseforge. The key aspect I am taking from this is "you need the maven identifer, it does not need to be the exact one". 

I would assume I can just use the first author as the groupID then? The rest I have managed. 

Yes, if I end up using this, I will credit the authors.

**Comment by system-operator** [comment]
Ok. Great help thank you.
