### ISSUE TITLE
Forge Versions

### ISSUE THREAD

**Issue by spigotdev** [WesterosCraftCode/ElectronLauncher#18]
Doesn't work on any Forge versions older than 1.9.

It's not the Forge version.json, something is malformed and incorrect in your code somewhere. But there is no logging for this aspect of the script. 

Verified working 1.9+ Forge
Verified BROKEN: Anything under 1.9

Seems like a TON of code to not work any variation or object key. You must be using string or something .

**Comment by spigotdev** [comment]
Actually appears to be related to the minecraftVersion field. 1.7.1 works, but 1.7.10 breaks. 

1.8 doesn't work at all, and 1.9, 1.9.1 DO work. 

Ideally at least the main release of version_manifest.json should be present and working eh?

I don't see any differences in the 1.7.10.json vs. the 1.6.4.json or the rest. 

Something is off here, and I can't quite pinpoint it. I might just fork the repo, and see if I can find it. But I have spent almost 6 hours looking. :()

**Comment by spigotdev** [comment]
By any chances are not using key's somewhere? Is it searching for "first occurence of" in any instance of the processbuilder or assetguard?

**Comment by spigotdev** [comment]
When changing to basically any other version thats old:
![image](https://user-images.githubusercontent.com/45136992/48669153-2b38fa00-eab3-11e8-9713-86f68c893229.png)

**Comment by spigotdev** [comment]
At a loss... I noticed you have a 1.9 server in the distribution server list, which works fine. 

1.6.4 Even works... Yet 1.7.10 is the best, and I am completely dumbfounded as to why its breaking.

**Comment by spigotdev** [comment]
Tracked to https://launchermeta.mojang.com/v1/packages/2e818dc89e364c7efcfa54bec7e873c5f00b3840/1.7.10.json

No idea on the diff's between say 1.6.4.json. No idea what doing.

**Comment by spigotdev** [comment]
```    validateClient(versionData, force = false){
        const self = this
        return new Promise((resolve, reject) => {
            const clientData = versionData.downloads.client
            const version = versionData.id
            const targetPath = path.join(self.commonPath, 'versions', version)
            const targetFile = version + '.jar'

            let client = new Asset(version + ' client', clientData.sha1, clientData.size, clientData.url, path.join(targetPath, targetFile))

            if(!AssetGuard._validateLocal(client.to, 'sha1', client.hash) || force){
                self.files.dlqueue.push(client)
                self.files.dlsize += client.size*1
                resolve()
            } else {
                resolve()
            }
        })
    }```
versionData.id is trimming the 0? 

/shrug

**Comment by spigotdev** [comment]
At a loss. Please help.

**Comment by spigotdev** [comment]
For some reason the versionData() method isn't working for 1.7.10.

That's as far as I can pinpoint it. No idea whats causing it.

**Comment by dscalzi** [comment]
Can you please send me your distribution.json.

**Comment by dscalzi** [comment]
It's working perfectly fine, if you're using a modified version of our code you'll need to link me to that.

**Comment by spigotdev** [comment]
No Im not using any modified code... I have a fork under my user with a local node http-server serving up the distribution.json. Only change made is the distro URL.

Literally breaks as soon as I change the minecraftVersion and displayed the error. 

Using master branch.

**Comment by spigotdev** [comment]
I have no changes to the distribution.json, other than minecraftVersion and a fresh copy of your code checked out. Same error as above after changing minecraftVersion. I can reproduce it 100% on master branch. 

1. Checkout Code.
2. Change minecraftVersion to "1.7.10" in distro and upload somewhere.
3. Launcher errors with "version" not found. 

[Preloader] Loading..
C:\Users\anonymous\D…\js\loggerutil.js:9 [ConfigManager] Successfully Loaded
C:\Users\anonymous\D…\js\loggerutil.js:9 [Preloader] Cleaned natives directory.
C:\Users\anonymous\D…\js\loggerutil.js:9 [Landing] Refreshing Mojang Statuses..
C:\Users\anonymous\D…\js\loggerutil.js:9 [UICore] UICore Initializing..
C:\Users\anonymous\D…\js\loggerutil.js:9 [Preloader] Loaded distribution index.
C:\Users\anonymous\D…\js\loggerutil.js:9 [Preloader] Determining default selected server..
C:\Users\anonymous\D…\js\loggerutil.js:9 [Landing] Refreshing Server Status
C:\Users\anonymous\D…\js\loggerutil.js:9 [Landing] Launching game..
C:\Users\anonymous\D…\js\loggerutil.js:9 [SysAEx] AssetExec Started
C:\Users\anonymous\D…\js\loggerutil.js:9 [SysAEx] java.runtime.version = 1.8.0_191-b12
C:\Users\anonymous\D…\js\loggerutil.js:9 [SysAEx] sun.arch.data.model = 64
C:\Users\anonymous\D…\js\loggerutil.js:9 [SysAEx] AssetExec Disconnected
C:\Users\anonymous\D…\js\loggerutil.js:9 [Landing] Refreshing Server Status
C:\Users\anonymous\D…s\assetguard.js:523 java.runtime.version = 1.8.0_191-b12
C:\Users\anonymous\D…s\assetguard.js:513 sun.arch.data.model = 64
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] AssetExec Started
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] %c[ConfigManager] color: #a02d2a; font-weight: bold Successfully Loaded
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] %c[DistroManager] color: #a02d2a; font-weight: bold Developer mode disabled.
C:\Users\anonymous\D…\js\loggerutil.js:9 [LaunchSuite] Validated distibution index.
uicore.js:29 The console is dark and full of terrors.
uicore.js:30 If you've been told to paste something here, you're being scammed.
uicore.js:31 Unless you know exactly what you're doing, close this window.
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] Preparing download of 1.7.10 assets.
C:\Users\anonymous\D…\js\loggerutil.js:9 [LaunchSuite] Version data loaded.
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] Downloading 1.7.10 asset index.
C:\Users\anonymous\D…\js\loggerutil.js:9 [LaunchSuite] Asset Validation Complete
C:\Users\anonymous\D…js\loggerutil.js:25 [LaunchSuite] Error during validation: Cannot read property 'sha1' of undefined
C:\Users\anonymous\D…\js\loggerutil.js:9 [LaunchSuite] Sending selected account (sys__op) to ProcessBuilder.
C:\Users\anonymous\D…\js\loggerutil.js:9 [ProcessBuilder] Using liteloader: false
C:\Users\anonymous\D…js\loggerutil.js:25 [LaunchSuite] Error during launch TypeError: Cannot read property 'id' of undefined
    at ProcessBuilder.classpathArg (C:\Users\anonymous\D…ocessbuilder.js:336)
    at ProcessBuilder.constructJVMArguments (C:\Users\anonymous\D…ocessbuilder.js:224)
    at ProcessBuilder.build (C:\Users\anonymous\D…rocessbuilder.js:50)
    at ChildProcess.aEx.on (landing.js:642)
    at ChildProcess.emit (events.js:182)
    at emit (internal/child_process.js:811)
    at process._tickCallback (internal/process/next_tick.js:63)
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] AssetExec Disconnected

**Comment by spigotdev** [comment]
It must be an issue with Forge for 1.7.10.

**Comment by spigotdev** [comment]
Confirmed and reproduced. Re-open?

**Comment by spigotdev** [comment]
All I see in your log, is that the logger method says "downloaded assets". 99% sure they aren't actually there. 

Could you provide a little more data on "works fine"? Seems I can't get it to launch at all. Even with the proper forge and its libraries(sub-modules).

**Comment by dscalzi** [comment]
sys__op bro, put the code back on github and let me take a look. The DMCA could not be stopped - as long as you put down the credits/fork there's no problem.

**Comment by spigotdev** [comment]
I will... tis fine. Just help. :|

**Comment by system-operator** [comment]
https://pastebin.com/8YR0wrTX

Unfortunately the new launcher is bloated, you need to adjust the assetguard or processbuilder scripts to use --userProperties {} instead of what it's using now. The above paste command line and this distribution.json ![](https://github.com/system-operator/ElectronLauncher/blob/master/app/assets/distribution.json)will load 1.7.10 (albeit without an icon?).
![image](https://user-images.githubusercontent.com/45136992/48671500-2e95ab00-eade-11e8-80df-4eb735d71ab2.png)

**Comment by system-operator** [comment]
Welp, I got much farther, and have now gotten to the correct distribution.json, however the assetguard.js appears to die randomly, or something... 

[AEx] WARN: Got 3014625 bytes for net.minecraftforge:forge:1.7.10-10.13.4.1558-1.7.10: Expected 4450992

C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] WARN: Got 2243036 bytes for com.google.guava:guava:17.0: Expected 217812

C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:90
                    throw err0;
                    ^

Error: EEXIST
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] : file already exists, mkdir 'C:\Users\anonymous\AppData\Roaming\.westeroscraft\common\libraries\commons-io\commons-io\2.4'
    at fs.mkdirSync (fs.js:872:
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] 3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
    at sync (C
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] :\Users\anonymous\Desktop\ElectronLauncher\node_modu
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] les\mkdirp\index.js:71:13)
    at sync (C:\Users\anonymous\De
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] sktop\ElectronLauncher\node_modules\mkdi
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] rp\index.js:77:24)
    at sync (C:\Users\anonymous
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] \Desktop\ElectronLauncher\node_modules\mkdi
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] rp\index.js:78:17)
    at sync (C:\Users\anonymo
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] us\Desktop\ElectronLauncher\node_modules\mkdirp\inde
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] x.js:78:17)
    at sync 
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] (C:\Users\anonymous\Desktop\ElectronLaunch
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] er\node_modules\mkdirp\index.js:78:17)
 
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx]    at sync (C:\Users\anonymous\Desktop
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] \ElectronLauncher\node_modules\mk
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] dirp\index.js:78:17)
    at sync (C:\Users\anon
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] ymous\Desktop\ElectronLauncher\node_modules\mkdirp
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] \index.js:78:17)
    at sync (C:\Users\anony
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] mous\Desktop\ElectronLauncher\node_modules\mkdirp\i
C:\Users\anonymous\Desktop\ElectronLauncher\app\assets\js\loggerutil.js:9 [AEx] ndex.js:78:17)

**Comment by system-operator** [comment]
Seems to be having heap errors etc now from mkdirp unfortunately..
```
[AEx] C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:90
                    throw err0;
                
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx]     ^

RangeError: Maximum call stack size exceeded
    at validateUint32 (internal/fs/utils.js:414:8)
    at fs.mkdirSync (fs.js:869:3)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:727:16)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_
C:\Users\anonymous\D…\js\loggerutil.js:9 [AEx] modules\mkdirp\index.js:78:17)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\anonymous\Desktop\ElectronLauncher\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\anonymous\Deskt
```
