### ISSUE TITLE
Have a modpack setup but crashses when it starts.

### ISSUE THREAD

**Issue by MaxIsH0t** [WesterosCraftCode/ElectronLauncher#25]
Hello, I have created a new modpack with this launcher and it does run but it crashses when it is loading.
[crash-2019-02-23_20.26.35-client.txt](https://github.com/WesterosCraftCode/ElectronLauncher/files/2897550/crash-2019-02-23_20.26.35-client.txt)
That's the crash report. Here is the pastebin: https://pastebin.com/9SQPD3NN

How could I solve this issue?

**Comment by dscalzi** [comment]
I can't tell unless you make your repository public (which is what you should be doing). You are likely missing libraries in your distribution file.
