### ISSUE TITLE
Add DEB x64

### ISSUE THREAD

**Issue by liberodark** [WesterosCraftCode/ElectronLauncher#3]
Hi,

Please add deb x64 is fully supported by electron packager.

Cordialy

**Comment by dscalzi** [comment]
Does AppImage not work on debian?

**Comment by liberodark** [comment]
no is not a problem is work and im not on debian.
but with deb x64 is more easy for make a port of your app !
:D is for help you

**Comment by dscalzi** [comment]
I will not be supporting prebuilt .deb binaries as AppImage seems to work fine. I have added a script to build .deb binaries to the package.json incase anyone wants to use it in a manual build. Note that since auto-updates likely would not be delivered to .deb installs.
