### ISSUE TITLE
Issue disabling shaderpack.

### ISSUE THREAD

**Issue by AegonThePrincess** [WesterosCraftCode/ElectronLauncher#7]
hello, I can't seem to change my shader (the onje included) to none.

**Comment by dscalzi** [comment]
This is not an issue with the launcher. Allocate more RAM or get a more powerful computer.

**Comment by dscalzi** [comment]
If I understand correctly, you cannot turn it off through the minecraft client. Edit optionsshaders.txt directly and make sure `shaderPack=OFF`.

`.westeroscraft/instances/WesterosCraft-1.11.1/optionsshaders.txt`

**Comment by dscalzi** [comment]
You can now do this in settings https://github.com/WesterosCraftCode/ElectronLauncher/releases/tag/v1.4.0
